import React, { useMemo, useState, createRoot } from './tiny-react.js';
import './styles.css';
const icon = (symbol) => ({ size = 16 }) => <span className="icon" style={{fontSize: size}} aria-hidden="true">{symbol}</span>;
const Bell=icon('◌'), CalendarDays=icon('□'), Check=icon('✓'), ChevronDown=icon('⌄'), ChevronLeft=icon('‹'), ChevronRight=icon('›'), CircleHelp=icon('?'), Clock3=icon('◷'), FileText=icon('▤'), Filter=icon('≡'), LayoutDashboard=icon('▦'), Mail=icon('✉'), MapPin=icon('⌖'), Menu=icon('☰'), MoreHorizontal=icon('•••'), Phone=icon('◔'), Plus=icon('+'), Search=icon('⌕'), Settings=icon('⚙'), Sparkles=icon('✦'), Target=icon('◎'), TrendingUp=icon('↗'), Users=icon('♙'), X=icon('×');

const prospectsSeed = [
  { id: 1, name: 'Mariana Ortega', initials: 'MO', city: 'Ciudad de México', phone: '+52 55 3421 8830', email: 'mariana.ortega@mail.com', type: 'Empresaria', source: 'Referido', date: '12 Sep 2026', owner: 'Lirios', state: 'Cita 2', needs: ['Protección familiar', 'Retiro'], notes: 'Busca equilibrar protección y ahorro para su familia.' },
  { id: 2, name: 'Andrés Valdés', initials: 'AV', city: 'Ciudad de México', phone: '+52 55 2384 9076', email: 'andres.valdes@mail.com', type: 'Profesional independiente', source: 'LinkedIn', date: '10 Sep 2026', owner: 'Lirios', state: 'Propuesta', needs: ['Protección patrimonial', 'Salud'], notes: 'Médico especialista, interesado en proteger su práctica.' },
  { id: 3, name: 'Sofía Navarro', initials: 'SN', city: 'Naucalpan', phone: '+52 55 8974 2661', email: 'sofia.navarro@mail.com', type: 'Empleada', source: 'Instagram', date: '08 Sep 2026', owner: 'Lirios', state: 'Seguimiento', needs: ['Ahorro', 'Educación'], notes: 'Desea comenzar un fondo para la universidad de su hija.' },
  { id: 4, name: 'Daniel Ríos', initials: 'DR', city: 'Ciudad de México', phone: '+52 55 7654 1287', email: 'daniel.rios@mail.com', type: 'Empresario', source: 'WhatsApp', date: '05 Sep 2026', owner: 'Lirios', state: 'Cita 1', needs: ['Retiro'], notes: 'Primera conversación de diagnóstico pendiente.' },
  { id: 5, name: 'Lucía Mendoza', initials: 'LM', city: 'Huixquilucan', phone: '+52 55 4902 1776', email: 'lucia.mendoza@mail.com', type: 'Profesional independiente', source: 'Evento', date: '02 Sep 2026', owner: 'Lirios', state: 'Contactado', needs: ['Salud'], notes: 'Contacto generado en evento de bienestar.' },
  { id: 6, name: 'Carlos Ibarra', initials: 'CI', city: 'Ciudad de México', phone: '+52 55 6655 9832', email: 'carlos.ibarra@mail.com', type: 'Empresario', source: 'Meta Ads', date: '29 Ago 2026', owner: 'Lirios', state: 'Nuevo', needs: [], notes: 'Solicitó información sobre seguro de vida.' },
];
const meetingsSeed = [
  { id: 1, time: '10:00', type: 'Cita 1', person: 'Daniel Ríos', initials: 'DR', mode: 'Videollamada', state: 'Confirmada', date: 'Hoy, 16 Sep' },
  { id: 2, time: '13:30', type: 'Cita 2', person: 'Mariana Ortega', initials: 'MO', mode: 'Presencial', state: 'Confirmada', date: 'Hoy, 16 Sep' },
  { id: 3, time: '17:00', type: 'Cita 1', person: 'Lucía Mendoza', initials: 'LM', mode: 'Videollamada', state: 'Programada', date: 'Mañana, 17 Sep' },
];
const followupsSeed = [
  { id: 1, person: 'Sofía Navarro', initials: 'SN', action: 'Enviar comparativo de opciones', due: 'Hoy', overdue: false },
  { id: 2, person: 'Andrés Valdés', initials: 'AV', action: 'Confirmar recepción de propuesta', due: 'Ayer', overdue: true },
  { id: 3, person: 'Carlos Ibarra', initials: 'CI', action: 'Realizar llamada inicial', due: '18 Sep', overdue: false },
];
const proposalsSeed = [
  { id: 1, person: 'Andrés Valdés', solution: 'Protección patrimonial integral', value: '$48,000', state: 'Presentada', date: '14 Sep 2026' },
  { id: 2, person: 'Mariana Ortega', solution: 'Plan de retiro y vida', value: '$36,000', state: 'Preparando', date: '16 Sep 2026' },
];
const nav = [
  ['Dashboard', LayoutDashboard], ['Prospectos', Users], ['Calendario', CalendarDays], ['Propuestas', FileText], ['Seguimientos', Clock3], ['Clientes', Sparkles], ['Indicadores', TrendingUp]
];
const states = ['Nuevo', 'Contactado', 'En diagnóstico', 'Cita 1', 'Cita 2', 'Propuesta', 'Seguimiento', 'Cliente', 'No interesado'];

function Avatar({ initials, tone = '' }) { return <span className={`avatar ${tone}`}>{initials}</span>; }
function Status({ children, type }) { return <span className={`status ${type || children.toLowerCase().replaceAll(' ', '-')}`}>{children}</span>; }
function SectionHeading({ eyebrow, title, text, action }) { return <div className="section-heading"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{text && <p className="intro">{text}</p>}</div>{action}</div>; }
function Modal({ title, children, onClose }) { return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e => e.stopPropagation()}><button className="icon-button modal-close" onClick={onClose}><X size={19}/></button><h2>{title}</h2>{children}</div></div>; }

function Dashboard({ meetings, followups, onNew, setActive }) {
 const overdue = followups.filter(f => f.overdue).length;
 return <>
  <SectionHeading eyebrow="Martes, 16 de septiembre" title="Buenos días, Lirios." text="Aquí tienes el pulso de tu proceso comercial." action={<button className="primary-button" onClick={() => onNew('prospect') }><Plus size={18}/> Nuevo prospecto</button>}/>
  <div className="metric-grid">
   {[['Prospectos activos','32','+12% este mes','blue'],['Citas esta semana','8','3 por realizar','sage'],['Propuestas activas','5','$184,000 estimados','sand'],['Clientes nuevos','3','Meta mensual: 6','blue']].map(([label,num,sub,t])=><article className={`metric-card ${t}`} key={label}><p>{label}</p><strong>{num}</strong><span>{sub}</span></article>)}
  </div>
  <section className="today-section"><div className="section-row"><div><p className="eyebrow">Prioridad</p><h2>Qué debes hacer hoy</h2></div><button className="text-button" onClick={() => setActive('Calendario')}>Ver agenda <ChevronRight size={16}/></button></div>
  <div className="today-grid"><article className="task-panel appointments"><div className="panel-label"><CalendarDays size={17}/> Citas del día <b>{meetings.filter(m=>m.date.includes('Hoy')).length}</b></div>{meetings.filter(m=>m.date.includes('Hoy')).map(m=><div className="appointment" key={m.id}><time>{m.time}</time><span className={`meeting-line ${m.type === 'Cita 2' ? 'second' : ''}`}></span><Avatar initials={m.initials}/><div><strong>{m.person}</strong><small>{m.type} · {m.mode}</small></div><Status type={m.type === 'Cita 2' ? 'cita-2' : 'cita-1'}>{m.type}</Status></div>)}<button className="add-row" onClick={() => onNew('meeting')}><Plus size={16}/> Agregar cita</button></article>
  <article className="task-panel"><div className="panel-label"><Clock3 size={17}/> Seguimientos <b>{followups.length}</b>{overdue > 0 && <em>{overdue} atrasado</em>}</div>{followups.slice(0,3).map(f=><div className="followup" key={f.id}><Avatar initials={f.initials}/><div><strong>{f.person}</strong><small>{f.action}</small></div><span className={f.overdue ? 'late' : ''}>{f.due}</span><button className="check-button" title="Completar"><Check size={15}/></button></div>)}<button className="add-row" onClick={() => onNew('followup')}><Plus size={16}/> Agregar seguimiento</button></article></div></section>
  <section className="insights-grid"><article className="chart-card"><div className="section-row"><div><p className="eyebrow">Actividad comercial</p><h2>Tu embudo, este mes</h2></div><button className="select-button">Septiembre <ChevronDown size={15}/></button></div><div className="funnel"><div style={{width:'100%'}}><span>Prospectos</span><b>42</b></div><div style={{width:'80%'}}><span>Citas realizadas</span><b>26</b></div><div style={{width:'59%'}}><span>Propuestas</span><b>15</b></div><div style={{width:'34%'}}><span>Cierres</span><b>8</b></div></div></article><article className="conversion-card"><p className="eyebrow">Conversión comercial</p><div className="conversion-circle"><strong>19<span>%</span></strong></div><h3>Vas por buen camino</h3><p>Tu conversión está 3 puntos por encima del mes anterior.</p><button className="text-button" onClick={() => setActive('Indicadores')}>Ver indicadores <ChevronRight size={16}/></button></article></section>
 </>;
}
function Prospects({ prospects, setProspects, onNew, openProfile }) {
 const [query,setQuery]=useState(''); const [filter,setFilter]=useState('Todos');
 const shown=useMemo(()=>prospects.filter(p=>(filter==='Todos'||p.state===filter)&&`${p.name} ${p.city} ${p.email} ${p.phone}`.toLowerCase().includes(query.toLowerCase())),[prospects,query,filter]);
 return <><SectionHeading eyebrow="Gestión comercial" title="Prospectos" text="Acompaña cada conversación desde el primer contacto." action={<button className="primary-button" onClick={()=>onNew('prospect')}><Plus size={18}/> Nuevo prospecto</button>}/><div className="table-card"><div className="table-tools"><label className="search-box"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nombre, correo, ciudad..."/></label><label className="filter-select"><Filter size={16}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option>{states.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>Prospecto</th><th>Tipo</th><th>Fuente</th><th>Fecha de ingreso</th><th>Estado</th><th></th></tr></thead><tbody>{shown.map(p=><tr key={p.id} onClick={()=>openProfile(p)}><td><div className="person"><Avatar initials={p.initials}/><div><strong>{p.name}</strong><small>{p.city}</small></div></div></td><td>{p.type}</td><td>{p.source}</td><td>{p.date}</td><td><Status>{p.state}</Status></td><td><button className="icon-button"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div>{shown.length===0&&<div className="empty">No encontramos prospectos con esos criterios.</div>}</div></>;
}
function Calendar({ meetings, onNew }) { const days = Array.from({length:30},(_,i)=>i+1); return <><SectionHeading eyebrow="Septiembre 2026" title="Calendario" text="Organiza tus conversaciones con intención." action={<button className="primary-button" onClick={()=>onNew('meeting')}><Plus size={18}/> Nueva cita</button>}/><div className="calendar-layout"><article className="calendar-card"><div className="calendar-tools"><button className="icon-button"><ChevronLeft size={18}/></button><strong>Septiembre 2026</strong><button className="icon-button"><ChevronRight size={18}/></button><div/><button className="view-toggle active">Mes</button><button className="view-toggle">Semana</button></div><div className="calendar-grid">{['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(d=><b key={d}>{d}</b>)}{Array.from({length:7},(_,i)=><span key={'blank'+i}></span>)}{days.map(d=><div className={`day ${d===16?'today':''}`} key={d}><span>{d}</span>{d===16&&<><small className="event cita1">10:00 · Daniel Ríos</small><small className="event cita2">13:30 · Mariana O.</small></>}{d===17&&<small className="event cita1">17:00 · Lucía M.</small>}{d===21&&<small className="event cita2">11:00 · Sofía N.</small>}</div>)}</div></article><aside className="agenda-card"><p className="eyebrow">Hoy · 16 sep</p><h2>Agenda del día</h2>{meetings.filter(m=>m.date.includes('Hoy')).map(m=><div className="agenda-meeting" key={m.id}><span className={m.type==='Cita 2'?'dot sage':'dot'}></span><div><strong>{m.time} · {m.person}</strong><small>{m.type} · {m.mode}</small></div></div>)}<hr/><p className="legend"><i></i> Cita 1 <i className="sage"></i> Cita 2</p></aside></div></> }
function Proposals({ proposals, onNew }) { return <><SectionHeading eyebrow="Soluciones a medida" title="Propuestas" text="Da seguimiento a cada solución presentada." action={<button className="primary-button" onClick={()=>onNew('proposal')}><Plus size={18}/> Nueva propuesta</button>}/><div className="proposal-grid">{proposals.map(p=><article className="proposal-card" key={p.id}><div className="card-top"><Status>{p.state}</Status><button className="icon-button"><MoreHorizontal size={18}/></button></div><h2>{p.person}</h2><p>{p.solution}</p><div className="proposal-value"><span>Valor estimado</span><strong>{p.value}</strong></div><footer><CalendarDays size={15}/> Seguimiento · {p.date}</footer></article>)}<button className="new-card" onClick={()=>onNew('proposal')}><Plus size={20}/><strong>Crear propuesta</strong><span>Registra una nueva solución</span></button></div></> }
function Followups({ followups, onNew }) { return <><SectionHeading eyebrow="Cuidar cada conversación" title="Seguimientos" text="Nunca pierdas de vista una próxima acción." action={<button className="primary-button" onClick={()=>onNew('followup')}><Plus size={18}/> Seguimiento</button>}/><div className="followup-list">{followups.map(f=><article className="followup-wide" key={f.id}><button className="check-button"><Check size={16}/></button><Avatar initials={f.initials}/><div className="wide-main"><strong>{f.person}</strong><span>{f.action}</span></div><div><small>Próximo contacto</small><strong className={f.overdue?'late':''}>{f.due}</strong></div><button className="icon-button"><MoreHorizontal size={18}/></button></article>)}</div></> }
function Clients() { return <><SectionHeading eyebrow="Relaciones que permanecen" title="Clientes" text="Acompaña y revisa cada protección contratada." action={<button className="primary-button"><Plus size={18}/> Nuevo cliente</button>}/><div className="empty-state"><Sparkles size={28}/><h2>Tu cartera empieza aquí</h2><p>Cuando un prospecto acepte una propuesta, podrás convertirlo en cliente y programar su próxima revisión.</p></div></> }
function Indicators() { const cards=[['Prospectos nuevos','42'],['Contactados','31'],['Citas 1','18'],['Citas 2','12'],['Propuestas','15'],['Clientes','8'],['Tasa de conversión','19%'],['Valor estimado','$184,000']]; return <><SectionHeading eyebrow="Visión del negocio" title="Indicadores" text="Entiende el ritmo y la salud de tu proceso comercial." action={<button className="select-button">Este mes <ChevronDown size={15}/></button>}/><div className="indicator-grid">{cards.map(([a,b])=><article key={a}><p>{a}</p><strong>{b}</strong><span>↗ 12% vs. mes anterior</span></article>)}</div><article className="chart-card line-chart"><div className="section-row"><div><p className="eyebrow">Tendencia</p><h2>Actividad de septiembre</h2></div></div><div className="bars">{[38,58,44,75,62,92,80,55,69,88,74,96].map((h,i)=><div key={i} style={{height:`${h}%`}}><span></span></div>)}</div><div className="bar-labels"><span>Sem 1</span><span>Sem 2</span><span>Sem 3</span><span>Sem 4</span></div></article></> }
function Profile({ prospect, onClose, setProspects }) { const [tab,setTab]=useState('Resumen'); const updateState=s=>setProspects(ps=>ps.map(p=>p.id===prospect.id?{...p,state:s}:p)); return <div className="profile"><button className="back-button" onClick={onClose}><ChevronLeft size={18}/> Volver a prospectos</button><div className="profile-head"><Avatar initials={prospect.initials}/><div><p className="eyebrow">Prospecto · {prospect.source}</p><h1>{prospect.name}</h1><p>{prospect.type} · {prospect.city}</p></div><div className="profile-actions"><select value={prospect.state} onChange={e=>updateState(e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select><button className="primary-button"><Plus size={17}/> Nueva acción</button></div></div><div className="tabs">{['Resumen','Diagnóstico','Citas','Propuestas','Notas'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Resumen'?<div className="profile-grid"><section className="profile-card"><h2>Información de contacto</h2><p><Phone size={16}/>{prospect.phone}</p><p><Mail size={16}/>{prospect.email}</p><p><MapPin size={16}/>{prospect.city}</p><hr/><h2>Necesidades detectadas</h2><div className="chips">{prospect.needs.length?prospect.needs.map(n=><span key={n}>{n}</span>):<span>Aún por definir</span>}</div></section><section className="profile-card timeline"><h2>Historial</h2><div><i></i><p><small>Hoy · 09:20</small><strong>Seguimiento programado</strong><span>Enviar comparativo de opciones.</span></p></div><div><i></i><p><small>14 Sep · 13:30</small><strong>Propuesta en preparación</strong><span>Plan de protección a medida.</span></p></div><div><i></i><p><small>10 Sep · 11:00</small><strong>Diagnóstico registrado</strong><span>{prospect.notes}</span></p></div></section></div>:<section className="empty-state compact"><Target size={26}/><h2>{tab} de {prospect.name}</h2><p>Este espacio está preparado para registrar y consultar la información de {tab.toLowerCase()}.</p></section>}</div> }

function App(){
 const [active,setActive]=useState('Dashboard'),[prospects,setProspects]=useState(prospectsSeed),[meetings,setMeetings]=useState(meetingsSeed),[followups,setFollowups]=useState(followupsSeed),[proposals,setProposals]=useState(proposalsSeed),[modal,setModal]=useState(null),[profile,setProfile]=useState(null),[mobile,setMobile]=useState(false);
 const submit = e => { e.preventDefault(); const data=new FormData(e.currentTarget); if(modal==='prospect'){const name=data.get('name')||'Nuevo prospecto';setProspects([{id:Date.now(),name,initials:name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase(),city:data.get('city')||'Ciudad de México',phone:data.get('phone')||'—',email:data.get('email')||'—',type:data.get('type'),source:data.get('source'),date:'16 Sep 2026',owner:'Lirios',state:'Nuevo',needs:[],notes:''},...prospects]);setActive('Prospectos')} if(modal==='meeting'){setMeetings([...meetings,{id:Date.now(),time:data.get('time')||'09:00',type:data.get('type'),person:data.get('person')||'Nuevo prospecto',initials:'NP',mode:data.get('mode'),state:'Programada',date:'Hoy, 16 Sep'}])} if(modal==='followup'){setFollowups([...followups,{id:Date.now(),person:data.get('person')||'Nuevo prospecto',initials:'NP',action:data.get('action')||'Nueva acción',due:data.get('due')||'Hoy',overdue:false}])} if(modal==='proposal'){setProposals([...proposals,{id:Date.now(),person:data.get('person')||'Nuevo prospecto',solution:data.get('solution')||'Solución personalizada',value:data.get('value')||'$0',state:'Preparando',date:'16 Sep 2026'}])} setModal(null); };
 const Field=({label,name,type='text',children,required})=><label className="form-field">{label}{children||<input name={name} type={type} required={required}/>}</label>;
 const form = modal && <Modal title={modal==='prospect'?'Nuevo prospecto':modal==='meeting'?'Nueva cita':modal==='followup'?'Nuevo seguimiento':'Nueva propuesta'} onClose={()=>setModal(null)}><form onSubmit={submit} className="form-grid">{modal==='prospect'&&<><Field label="Nombre completo" name="name" required/><Field label="WhatsApp" name="phone" type="tel"/><Field label="Correo" name="email" type="email"/><Field label="Ciudad" name="city"/><Field label="Tipo de prospecto"><select name="type">{['Empresario','Profesional independiente','Empleado','Otro'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Fuente"><select name="source">{['WhatsApp','Instagram','LinkedIn','Referido','Meta Ads','Evento','Otro'].map(x=><option key={x}>{x}</option>)}</select></Field></>}{modal==='meeting'&&<><Field label="Prospecto" name="person"/><Field label="Tipo de cita"><select name="type"><option>Cita 1</option><option>Cita 2</option></select></Field><Field label="Fecha" name="date" type="date"/><Field label="Hora" name="time" type="time"/><Field label="Modalidad"><select name="mode"><option>Videollamada</option><option>Presencial</option><option>Telefónica</option></select></Field></>}{modal==='followup'&&<><Field label="Prospecto" name="person"/><Field label="Acción" name="action"/><Field label="Próximo contacto" name="due" type="date"/></>}{modal==='proposal'&&<><Field label="Prospecto" name="person"/><Field label="Producto / solución" name="solution"/><Field label="Valor estimado" name="value"/></>}<div className="form-actions"><button type="button" className="secondary-button" onClick={()=>setModal(null)}>Cancelar</button><button className="primary-button" type="submit">Guardar</button></div></form></Modal>;
 if(profile) return <><aside className={`sidebar ${mobile?'open':''}`}> <div className="brand"><span>L</span><div><strong>LIRIOS</strong><small>Agencia de Vida</small></div></div>{nav.map(([n,I])=><button className={active===n?'active':''} key={n} onClick={()=>{setActive(n);setProfile(null)}}><I size={19}/>{n}</button>)}</aside><main className="main profile-main"><Profile prospect={profile} onClose={()=>setProfile(null)} setProspects={setProspects}/></main></>;
 const content={Dashboard:<Dashboard meetings={meetings} followups={followups} onNew={setModal} setActive={setActive}/>,Prospectos:<Prospects prospects={prospects} setProspects={setProspects} onNew={setModal} openProfile={setProfile}/>,Calendario:<Calendar meetings={meetings} onNew={setModal}/>,Propuestas:<Proposals proposals={proposals} onNew={setModal}/>,Seguimientos:<Followups followups={followups} onNew={setModal}/>,Clientes:<Clients/>,Indicadores:<Indicators/>}[active];
 return <div className="app"><aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><span>L</span><div><strong>LIRIOS</strong><small>Agencia de Vida</small></div><button className="mobile-close icon-button" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([n,I])=><button className={active===n?'active':''} key={n} onClick={()=>{setActive(n);setMobile(false)}}><I size={19}/>{n}</button>)}</nav><div className="sidebar-bottom"><button><CircleHelp size={18}/> Centro de ayuda</button><button><Settings size={18}/> Ajustes</button><div className="user"><Avatar initials="LA"/><div><strong>Lirios Agencia</strong><small>Consultora</small></div><ChevronDown size={15}/></div></div></aside><main className="main"><header className="topbar"><button className="menu-button icon-button" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">LIRIOS <span>/</span> {active}</div><div className="top-actions"><button className="quick-button" onClick={()=>setModal('meeting')}><Plus size={16}/> Nueva cita</button><button className="icon-button notification"><Bell size={19}/><i></i></button></div></header><div className="page-content">{content}</div></main>{form}</div>
}
createRoot(document.getElementById('root')).render(<App/>);
